# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Open Up' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for Open Up

pod 'Alamofire'

end
